project:
  type: website
  output-dir: docs

website:
  title: "Denis A. Engemann"
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Denis A. Engemann
      - href: about.qmd
        text: About Me
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    page-layout: full



